helmDefaults:
  createNamespace: true
  wait: true
  atomic: true
  timeout: 300

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: external-dns
    url: https://charts.bitnami.com/bitnami
  - name: argocd
    url: https://argoproj.github.io/argo-helm
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.11.3"
    values:
      - helm-values/nginx.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: "1.18.2"
    values:
      - helm-values/cert-manager.yaml
    needs: 
      - ingress-nginx/ingress-nginx

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    values:
      - helm-values/external-dns.yaml
    needs: 
      - ingress-nginx/ingress-nginx
      
  - name: argocd
    namespace: argocd
    chart: argocd/argo-cd
    version: "9.0.5" 
    values:
      - helm-values/argocd-values.yaml
    needs: 
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cert-manager

  - name: prometheus
    namespace: prometheus
    chart: prometheus/prometheus
    version: "27.42.2"
    values:
      - helm-values/prometheus.yaml
    needs: 
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cert-manager

  - name: grafana
    namespace: grafana
    chart: grafana/grafana
    version: "10.1.4"
    values:
      - helm-values/grafana.yaml
    needs: 
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cert-manager