apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
  namespace: prometheus
  labels:
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
