# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx1
  namespace: apps
spec:
  secretName: nginx1
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - 'lab.ridwanahmed.com'
  - 'argocd.lab.ridwanahmed.com'
