# .checkov.yaml
framework: terraform

check:
  - CKV_AWS_260   # ALB needs port 80 open to perform HTTP->HTTPS redirect; app still served over 443
  - CKV2_AWS_38   # Route53 DNSSEC not required for demo subdomain/zone
  - CKV2_AWS_39   # Route53 query logging not necessary for demo traffic
  - CKV2_AWS_5    # Temporary SGs may be unattached during scaffold/plan in a demo
  - CKV_AWS_91    # ALB access logging not set up yet (needs S3 bucket & policy)
  - CKV_AWS_158   # CloudWatch Log Group KMS encryption deferred for demo
  - CKV_AWS_192   # WAF Log4j protection (add KnownBadInputs rule group later)
  - CKV2_AWS_31   # WAF logging configuration (Firehose/CWL wiring pending)
  - CKV2_AWS_11   # VPC Flow Logs not enabled yet (S3/CWL + role needed)
  - CKV2_AWS_12   # Default SG lockdown (manage aws_default_security_group later)
  - CKV2_AWS_76   # ALB requires WAF AMR for Log4j (follows from CKV_AWS_192)
  - CKV_AWS_338
  - CKV_AWS_249
  - CKV_AWS_65
  - CKV_AWS_51
  - CKV_AWS_150
  - CKV_AWS_136
  - CKV_TF_1
  - CKV_TF_2